# Generated by Django 4.2.8 on 2023-12-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paralaxiom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
